export const STATUS = {
  DRAFT: "DRAFT",
  WAITING_GA_ESTIMATE: "WAITING_GA_ESTIMATE",
  WAITING_JV_APPROVAL: "WAITING_JV_APPROVAL",
  JV_APPROVED: "JV_APPROVED",
  JV_REJECTED: "JV_REJECTED",
  WAITING_EMP_SUMMARY: "WAITING_EMP_SUMMARY",
  WAITING_GA_ACTUAL_COST: "WAITING_GA_ACTUAL_COST",
  WAITING_CLAIM_ALLOWANCE: "WAITING_CLAIM_ALLOWANCE",
  GA_COMPLETED: "GA_COMPLETED",
  WAITING_PLANNER_COST_ANALYSIS: "WAITING_PLANNER_COST_ANALYSIS",
  COMPLETED: "COMPLETED",
  WAITING: "WAITING",
  CANCELLED: "CANCELLED",
} as const

//using for query with status = "WAITING" to include all waiting statuses without waiting_planner_cost_analysis
export const WAITING_STATUSES = [
  STATUS.WAITING_GA_ESTIMATE,
  STATUS.WAITING_JV_APPROVAL,
  STATUS.WAITING_EMP_SUMMARY,
  STATUS.WAITING_GA_ACTUAL_COST,
  STATUS.WAITING_CLAIM_ALLOWANCE,
] as [string, string, string, string, string]

export const PLANNER_ACTIONS = {
  SUBMIT: "SUBMIT",
  GA_ESTIMATE_DONE: "GA_ESTIMATE_DONE",
  JV_APPROVE: "JV_APPROVE",
  JV_REJECT: "JV_REJECT",
  APPROVE_ONE_JV: "APPROVE_ONE_JV",
  EMP_SUMMARY_DONE: "EMP_SUMMARY_DONE",
  GA_ACTUAL_DONE: "GA_ACTUAL_DONE",
  CLAIM_ALLOWANCE: "CLAIM_ALLOWANCE",
  GA_FINALIZE_DONE: "GA_FINALIZE_DONE",
  PLANNER_ANALYSIS_DONE: "PLANNER_ANALYSIS_DONE",
  CANCEL: "CANCEL",
} as const

export type PlannerStatus = (typeof STATUS)[keyof typeof STATUS]
export type PlannerAction = (typeof PLANNER_ACTIONS)[keyof typeof PLANNER_ACTIONS]
